<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员信息"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"用户管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"用户管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"法律法规管理",
			            "menuJump":"列表",
			            "tableName":"falvgagui"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
"修改",
			                "删除"
			            ],
			            "menu":"法律法规留言管理",
			            "menuJump":"列表",
			            "tableName":"falvgaguiLiuyan"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"法律法规收藏管理",
			            "menuJump":"列表",
			            "tableName":"falvgaguiCollection"
			        }
			    ],
			    "menu":"法律法规管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"司法解释管理",
			            "menuJump":"列表",
			            "tableName":"shifajieshi"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
"修改",
			                "删除"
			            ],
			            "menu":"司法解释留言管理",
			            "menuJump":"列表",
			            "tableName":"shifajieshiLiuyan"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"司法解释收藏管理",
			            "menuJump":"列表",
			            "tableName":"shifajieshiCollection"
			        }
			    ],
			    "menu":"司法解释管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"部门规章管理",
                        "menuJump":"列表",
                        "tableName":"bumenguizhang"
                    }
                ],
                "menu":"部门规章管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"规范文件管理",
                        "menuJump":"列表",
                        "tableName":"guifanwenjian"
                    }
                ],
                "menu":"规范文件管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"行政法规管理",
                        "menuJump":"列表",
                        "tableName":"xingzhengfagui"
                    }
                ],
                "menu":"行政法规管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"政策文件管理",
                        "menuJump":"列表",
                        "tableName":"zhengchengwenjian"
                    }
                ],
                "menu":"政策文件管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"轮播图管理",
			            "menuJump":"列表",
			            "tableName":"config"
			        }
			    ],
			    "menu":"轮播图管理"
			}
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
	    "backMenu":[
			{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"法律法规管理",
			            "menuJump":"列表",
			            "tableName":"falvgagui"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"法律法规留言管理",
			            "menuJump":"列表",
			            "tableName":"falvgaguiLiuyan"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"法律法规收藏管理",
			            "menuJump":"列表",
			            "tableName":"falvgaguiCollection"
			        }
			    ],
			    "menu":"法律法规管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"司法解释管理",
			            "menuJump":"列表",
			            "tableName":"shifajieshi"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"司法解释留言管理",
			            "menuJump":"列表",
			            "tableName":"shifajieshiLiuyan"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"司法解释收藏管理",
			            "menuJump":"列表",
			            "tableName":"shifajieshiCollection"
			        }
			    ],
			    "menu":"司法解释管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"部门规章管理",
	                    "menuJump":"列表",
	                    "tableName":"bumenguizhang"
	                }
	            ],
	            "menu":"部门规章管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"规范文件管理",
	                    "menuJump":"列表",
	                    "tableName":"guifanwenjian"
	                }
	            ],
	            "menu":"规范文件管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"行政法规管理",
	                    "menuJump":"列表",
	                    "tableName":"xingzhengfagui"
	                }
	            ],
	            "menu":"行政法规管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"政策文件管理",
	                    "menuJump":"列表",
	                    "tableName":"zhengchengwenjian"
	                }
	            ],
	            "menu":"政策文件管理"
	        }
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"用户",
	    "tableName":"yonghu"
	}
];

var hasMessage = '';
